City.create!([
  {name: "Adlešiči", post_num: 8341},
  {name: "Ajdovščina", post_num: 5270},
  {name: "Ankaran/Ancarano", post_num: 6280},
  {name: "Apače", post_num: 9253},
  {name: "Artiče", post_num: 8253},
  {name: "Begunje na Gorenjskem", post_num: 4275},
  {name: "Begunje pri Cerknici", post_num: 1382},
  {name: "Beltinci", post_num: 9231},
  {name: "Benedikt", post_num: 2234},
  {name: "Bistrica ob Dravi", post_num: 2345},
  {name: "Bistrica ob Sotli", post_num: 3256},
  {name: "Bizeljsko", post_num: 8259},
  {name: "Blagovica", post_num: 1223},
  {name: "Blanca", post_num: 8283},
  {name: "Bled", post_num: 4260},
  {name: "Blejska Dobrava", post_num: 4273},
  {name: "Bodonci", post_num: 9265},
  {name: "Bogojina", post_num: 9222},
  {name: "Bohinjska Bela", post_num: 4263},
  {name: "Bohinjska Bistrica", post_num: 4264},
  {name: "Bohinjsko jezero", post_num: 4265},
  {name: "Borovnica", post_num: 1353},
  {name: "Boštanj", post_num: 8294},
  {name: "Bovec", post_num: 5230},
  {name: "Branik", post_num: 5295},
  {name: "Braslovče", post_num: 3314},
  {name: "Breginj", post_num: 5223},
  {name: "Brestanica", post_num: 8280},
  {name: "Bresternica", post_num: 2354},
  {name: "Brezje", post_num: 4243},
  {name: "Brezovica pri Ljubljani", post_num: 1351},
  {name: "Brežice", post_num: 8250},
  {name: "Brnik - Aerodrom", post_num: 4210},
  {name: "Brusnice", post_num: 8321},
  {name: "Buče", post_num: 3255},
  {name: "Bučka ", post_num: 8276},
  {name: "Cankova", post_num: 9261},
  {name: "Celje ", post_num: 3000},
  {name: "Celje2", post_num: 3001},
  {name: "Cerklje na Gorenjskem", post_num: 4207},
  {name: "Cerklje ob Krki", post_num: 8263},
  {name: "Cerknica", post_num: 1380},
  {name: "Cerkno", post_num: 5282},
  {name: "Cerkvenjak", post_num: 2236},
  {name: "Ceršak", post_num: 2215},
  {name: "Cirkovce", post_num: 2326},
  {name: "Cirkulane", post_num: 2282},
  {name: "Col", post_num: 5273},
  {name: "Čatež ob Savi", post_num: 8251},
  {name: "Čemšenik", post_num: 1413},
  {name: "Čepovan", post_num: 5253},
  {name: "Črenšovci", post_num: 9232},
  {name: "Črna na Koroškem", post_num: 2393},
  {name: "Črni Kal", post_num: 6275},
  {name: "Črni Vrh nad Idrijo", post_num: 5274},
  {name: "Črniče", post_num: 5262},
  {name: "Črnomelj", post_num: 8340},
  {name: "Dekani", post_num: 6271},
  {name: "Deskle", post_num: 5210},
  {name: "Destrnik", post_num: 2253},
  {name: "Divača", post_num: 6215},
  {name: "Dob", post_num: 1233},
  {name: "Dobje pri Planini", post_num: 3224},
  {name: "Dobova", post_num: 8257},
  {name: "Dobovec", post_num: 1423},
  {name: "Dobravlje", post_num: 5263},
  {name: "Dobrna", post_num: 3204},
  {name: "Dobrnič", post_num: 8211},
  {name: "Dobrova", post_num: 1356},
  {name: "Dobrovnik/Dobronak ", post_num: 9223},
  {name: "Dobrovo v Brdih", post_num: 5212},
  {name: "Dol pri Hrastniku", post_num: 1431},
  {name: "Dol pri Ljubljani", post_num: 1262},
  {name: "Dole pri Litiji", post_num: 1273},
  {name: "Dolenja vas", post_num: 1331},
  {name: "Dolenjske Toplice", post_num: 8350},
  {name: "Domžale", post_num: 1230},
  {name: "Dornava", post_num: 2252},
  {name: "Dornberk", post_num: 5294},
  {name: "Draga", post_num: 1319},
  {name: "Dragatuš", post_num: 8343},
  {name: "Dramlje", post_num: 3222},
  {name: "Dravograd", post_num: 2370},
  {name: "Duplje", post_num: 4203},
  {name: "Dutovlje", post_num: 6221},
  {name: "Dvor", post_num: 8361},
  {name: "Fala", post_num: 2343},
  {name: "Fokovci", post_num: 9208},
  {name: "Fram", post_num: 2313},
  {name: "Frankolovo", post_num: 3213},
  {name: "Gabrovka", post_num: 1274},
  {name: "Globoko", post_num: 8254},
  {name: "Godovič", post_num: 5275},
  {name: "Golnik", post_num: 4204},
  {name: "Gomilsko", post_num: 3303},
  {name: "Gorenja vas", post_num: 4224},
  {name: "Gorica pri Slivnici", post_num: 3263},
  {name: "Gorišnica", post_num: 2272},
  {name: "Gornja Radgona", post_num: 9250},
  {name: "Gornji Grad", post_num: 3342},
  {name: "Gozd Martuljek", post_num: 4282},
  {name: "Gračišče", post_num: 6272},
  {name: "Grad", post_num: 9264},
  {name: "Gradac", post_num: 8332},
  {name: "Grahovo", post_num: 1384},
  {name: "Grahovo ob Bači", post_num: 5242},
  {name: "Grgar", post_num: 5251},
  {name: "Griže", post_num: 3302},
  {name: "Grobelno", post_num: 3231},
  {name: "Grosuplje", post_num: 1290},
  {name: "Hajdina", post_num: 2288},
  {name: "Hinje", post_num: 8362},
  {name: "Hoče", post_num: 2311},
  {name: "Hodoš/Hodos", post_num: 9205},
  {name: "Horjul", post_num: 1354},
  {name: "Hotedršica", post_num: 1372},
  {name: "Hrastnik", post_num: 1430},
  {name: "Hruševje", post_num: 6225},
  {name: "Hrušica", post_num: 4276},
  {name: "Idrija", post_num: 5280},
  {name: "Ig", post_num: 1292},
  {name: "Ilirska Bistrica", post_num: 6250},
  {name: "Ilirska Bistrica-Trnovo", post_num: 6251},
  {name: "Ivančna Gorica", post_num: 1295},
  {name: "Ivanjkovci", post_num: 2259},
  {name: "Izlake", post_num: 1411},
  {name: "Izola/Isola", post_num: 6310},
  {name: "Jakobski Dol", post_num: 2222},
  {name: "Jarenina", post_num: 2221},
  {name: "Jelšane", post_num: 6254},
  {name: "Jesenice", post_num: 4270},
  {name: "Jesenice na Dolenjskem", post_num: 8261},
  {name: "Jurklošter", post_num: 3273},
  {name: "Jurovski Dol", post_num: 2223},
  {name: "Juršinci", post_num: 2256},
  {name: "Kal nad Kanalom", post_num: 5214},
  {name: "Kalobje", post_num: 3233},
  {name: "Kamna Gorica", post_num: 4246},
  {name: "Kamnica", post_num: 2351},
  {name: "Kamnik", post_num: 1241},
  {name: "Kanal", post_num: 5213},
  {name: "Kapele", post_num: 8258},
  {name: "Kapla", post_num: 2362},
  {name: "Kidričevo", post_num: 2325},
  {name: "Kisovec", post_num: 1412},
  {name: "Knežak", post_num: 6253},
  {name: "Kobarid", post_num: 5222},
  {name: "Kobilje", post_num: 9227},
  {name: "Kočevje", post_num: 1330},
  {name: "Kočevska Reka", post_num: 1338},
  {name: "Kog", post_num: 2276},
  {name: "Kojsko", post_num: 5211},
  {name: "Komen", post_num: 6223},
  {name: "Komenda", post_num: 1218},
  {name: "Koper/Capodistria ", post_num: 6000},
  {name: "Koper/Capodistria - poštni predali", post_num: 6001},
  {name: "Koprivnica", post_num: 8282},
  {name: "Kostanjevica na Krasu", post_num: 5296},
  {name: "Kostanjevica na Krki", post_num: 8311},
  {name: "Kostel", post_num: 1336},
  {name: "Košana", post_num: 6256},
  {name: "Kotlje", post_num: 2394},
  {name: "Kozina", post_num: 6240},
  {name: "Kozje", post_num: 3260},
  {name: "Kranj ", post_num: 4000},
  {name: "Kranj - poštni predali", post_num: 4001},
  {name: "Kranjska Gora", post_num: 4280},
  {name: "Kresnice", post_num: 1281},
  {name: "Križe", post_num: 4294},
  {name: "Križevci", post_num: 9206},
  {name: "Križevci pri Ljutomeru", post_num: 9242},
  {name: "Krka", post_num: 1301},
  {name: "Krmelj", post_num: 8296},
  {name: "Kropa", post_num: 4245},
  {name: "Krška vas", post_num: 8262},
  {name: "Krško", post_num: 8270},
  {name: "Kuzma", post_num: 9263},
  {name: "Laporje", post_num: 2318},
  {name: "Laško", post_num: 3270},
  {name: "Laze v Tuhinju", post_num: 1219},
  {name: "Lenart v Slovenskih goricah", post_num: 2230},
  {name: "Lendava/Lendva", post_num: 9220},
  {name: "Lesce", post_num: 4248},
  {name: "Lesično", post_num: 3261},
  {name: "Leskovec pri Krškem", post_num: 8273},
  {name: "Libeliče", post_num: 2372},
  {name: "Limbuš", post_num: 2341},
  {name: "Litija", post_num: 1270},
  {name: "Ljubečna", post_num: 3202},
  {name: "Ljubljana ", post_num: 1000},
  {name: "Ljubljana - poštni predali", post_num: 1001},
  {name: "Ljubljana - Črnuče", post_num: 1231},
  {name: "Ljubljana - Dobrunje", post_num: 1261},
  {name: "Ljubljana - Polje", post_num: 1260},
  {name: "Ljubljana - Šentvid", post_num: 1210},
  {name: "Ljubljana - Šmartno", post_num: 1211},
  {name: "Ljubno ob Savinji", post_num: 3333},
  {name: "Ljutomer", post_num: 9240},
  {name: "Loče", post_num: 3215},
  {name: "Log pod Mangartom", post_num: 5231},
  {name: "Log pri Brezovici", post_num: 1358},
  {name: "Logatec", post_num: 1370},
  {name: "Logatec", post_num: 1371},
  {name: "Loka pri Zidanem Mostu", post_num: 1434},
  {name: "Loka pri Žusmu", post_num: 3223},
  {name: "Lokev", post_num: 6219},
  {name: "Loški Potok", post_num: 1318},
  {name: "Lovrenc na Dravskem polju", post_num: 2324},
  {name: "Lovrenc na Pohorju", post_num: 2344},
  {name: "Luče", post_num: 3334},
  {name: "Lukovica", post_num: 1225},
  {name: "Mačkovci", post_num: 9202},
  {name: "Majšperk", post_num: 2322},
  {name: "Makole", post_num: 2321},
  {name: "Mala Nedelja", post_num: 9243},
  {name: "Malečnik", post_num: 2229},
  {name: "Marezige", post_num: 6273},
  {name: "Maribor ", post_num: 2000},
  {name: "Maribor - poštni predali", post_num: 2001},
  {name: "Marjeta na Dravskem polju", post_num: 2206},
  {name: "Markovci", post_num: 2281},
  {name: "Martjanci", post_num: 9221},
  {name: "Materija", post_num: 6242},
  {name: "Mavčiče", post_num: 4211},
  {name: "Medvode", post_num: 1215},
  {name: "Mengeš", post_num: 1234},
  {name: "Metlika", post_num: 8330},
  {name: "Mežica", post_num: 2392},
  {name: "Miklavž na Dravskem polju", post_num: 2204},
  {name: "Miklavž pri Ormožu", post_num: 2275},
  {name: "Miren", post_num: 5291},
  {name: "Mirna", post_num: 8233},
  {name: "Mirna Peč", post_num: 8216},
  {name: "Mislinja", post_num: 2382},
  {name: "Mojstrana", post_num: 4281},
  {name: "Mokronog", post_num: 8230},
  {name: "Moravče", post_num: 1251},
  {name: "Moravske Toplice", post_num: 9226},
  {name: "Most na Soči", post_num: 5216},
  {name: "Motnik", post_num: 1221},
  {name: "Mozirje", post_num: 3330},
  {name: "Murska Sobota ", post_num: 9000},
  {name: "Murska Sobota - poštni predali", post_num: 9001},
  {name: "Muta", post_num: 2366},
  {name: "Naklo", post_num: 4202},
  {name: "Nazarje", post_num: 3331},
  {name: "Notranje Gorice", post_num: 1357},
  {name: "Nova Cerkev", post_num: 3203},
  {name: "Nova Gorica ", post_num: 5000},
  {name: "Nova Gorica - poštni predali", post_num: 5001},
  {name: "Nova vas", post_num: 1385},
  {name: "Novo mesto", post_num: 8000},
  {name: "Novo mesto - poštni predali", post_num: 8001},
  {name: "Obrov", post_num: 6243},
  {name: "Odranci", post_num: 9233},
  {name: "Oplotnica", post_num: 2317},
  {name: "Orehova vas", post_num: 2312},
  {name: "Ormož", post_num: 2270},
  {name: "Ortnek", post_num: 1316},
  {name: "Osilnica", post_num: 1337},
  {name: "Otočec", post_num: 8222},
  {name: "Ožbalt", post_num: 2361},
  {name: "Pernica", post_num: 2231},
  {name: "Pesnica pri Mariboru", post_num: 2211},
  {name: "Petrovci", post_num: 9203},
  {name: "Petrovče", post_num: 3301},
  {name: "Piran/Pirano", post_num: 6330},
  {name: "Pišece", post_num: 8255},
  {name: "Pivka", post_num: 6257},
  {name: "Planina", post_num: 6232},
  {name: "Planina pri Sevnici", post_num: 3225},
  {name: "Pobegi", post_num: 6276},
  {name: "Podbočje", post_num: 8312},
  {name: "Podbrdo", post_num: 5243},
  {name: "Podčetrtek", post_num: 3254},
  {name: "Podgorci", post_num: 2273},
  {name: "Podgorje", post_num: 6216},
  {name: "Podgorje pri Slovenj Gradcu", post_num: 2381},
  {name: "Podgrad", post_num: 6244},
  {name: "Podkum", post_num: 1414},
  {name: "Podlehnik", post_num: 2286},
  {name: "Podnanos", post_num: 5272},
  {name: "Podnart", post_num: 4244},
  {name: "Podplat", post_num: 3241},
  {name: "Podsreda", post_num: 3257},
  {name: "Podvelka", post_num: 2363},
  {name: "Pohorje", post_num: 2208},
  {name: "Polenšak", post_num: 2257},
  {name: "Polhov Gradec", post_num: 1355},
  {name: "Poljane nad Škofjo Loko", post_num: 4223},
  {name: "Poljčane", post_num: 2319},
  {name: "Polšnik", post_num: 1272},
  {name: "Polzela", post_num: 3313},
  {name: "Ponikva", post_num: 3232},
  {name: "Portorož/Portorose", post_num: 6320},
  {name: "Postojna", post_num: 6230},
  {name: "Pragersko", post_num: 2331},
  {name: "Prebold", post_num: 3312},
  {name: "Preddvor", post_num: 4205},
  {name: "Prem", post_num: 6255},
  {name: "Preserje", post_num: 1352},
  {name: "Prestranek", post_num: 6258},
  {name: "Prevalje", post_num: 2391},
  {name: "Prevorje", post_num: 3262},
  {name: "Primskovo ", post_num: 1276},
  {name: "Pristava pri Mestinju", post_num: 3253},
  {name: "Prosenjakovci/Partosfalva", post_num: 9207},
  {name: "Prvačina", post_num: 5297},
  {name: "Ptuj", post_num: 2250},
  {name: "Ptujska Gora", post_num: 2323},
  {name: "Puconci", post_num: 9201},
  {name: "Rače", post_num: 2327},
  {name: "Radeče", post_num: 1433},
  {name: "Radenci", post_num: 9252},
  {name: "Radlje ob Dravi", post_num: 2360},
  {name: "Radomlje", post_num: 1235},
  {name: "Radovljica", post_num: 4240},
  {name: "Raka", post_num: 8274},
  {name: "Rakek", post_num: 1381},
  {name: "Rateče - Planica", post_num: 4283},
  {name: "Ravne na Koroškem", post_num: 2390},
  {name: "Rečica ob Savinji", post_num: 3332},
  {name: "Renče", post_num: 5292},
  {name: "Ribnica", post_num: 1310},
  {name: "Ribnica na Pohorju", post_num: 2364},
  {name: "Rimske Toplice", post_num: 3272},
  {name: "Rob", post_num: 1314},
  {name: "Ročinj", post_num: 5215},
  {name: "Rogaška Slatina", post_num: 3250},
  {name: "Rogašovci", post_num: 9262},
  {name: "Rogatec", post_num: 3252},
  {name: "Rovte", post_num: 1373},
  {name: "Ruše", post_num: 2342},
  {name: "Sava", post_num: 1282},
  {name: "Sečovlje/Sicciole", post_num: 6333},
  {name: "Selca", post_num: 4227},
  {name: "Selnica ob Dravi", post_num: 2352},
  {name: "Semič", post_num: 8333},
  {name: "Senovo", post_num: 8281},
  {name: "Senožeče", post_num: 6224},
  {name: "Sevnica", post_num: 8290},
  {name: "Sežana", post_num: 6210},
  {name: "Sladki Vrh", post_num: 2214},
  {name: "Slap ob Idrijci", post_num: 5283},
  {name: "Slovenj Gradec", post_num: 2380},
  {name: "Slovenska Bistrica", post_num: 2310},
  {name: "Slovenske Konjice", post_num: 3210},
  {name: "Smlednik", post_num: 1216},
  {name: "Soča", post_num: 5232},
  {name: "Sodražica", post_num: 1317},
  {name: "Solčava", post_num: 3335},
  {name: "Solkan", post_num: 5250},
  {name: "Sorica", post_num: 4229},
  {name: "Sovodenj", post_num: 4225},
  {name: "Spodnja Idrija", post_num: 5281},
  {name: "Spodnji Duplek", post_num: 2241},
  {name: "Spodnji Ivanjci", post_num: 9245},
  {name: "Središče ob Dravi", post_num: 2277},
  {name: "Srednja vas v Bohinju", post_num: 4267},
  {name: "Sromlje ", post_num: 8256},
  {name: "Srpenica", post_num: 5224},
  {name: "Stahovica", post_num: 1242},
  {name: "Stara Cerkev", post_num: 1332},
  {name: "Stari trg ob Kolpi", post_num: 8342},
  {name: "Stari trg pri Ložu", post_num: 1386},
  {name: "Starše", post_num: 2205},
  {name: "Stoperce", post_num: 2289},
  {name: "Stopiče", post_num: 8322},
  {name: "Stranice", post_num: 3206},
  {name: "Straža", post_num: 8351},
  {name: "Struge", post_num: 1313},
  {name: "Studenec", post_num: 8293},
  {name: "Suhor", post_num: 8331},
  {name: "Sv. Ana v Slovenskih goricah", post_num: 2233},
  {name: "Sv. Trojica v Slovenskih goricah", post_num: 2235},
  {name: "Sveti Duh na Ostrem Vrhu", post_num: 2353},
  {name: "Sveti Jurij ob Ščavnici", post_num: 9244},
  {name: "Sveti Štefan", post_num: 3264},
  {name: "Sveti Tomaž", post_num: 2258},
  {name: "Šalovci", post_num: 9204},
  {name: "Šempas", post_num: 5261},
  {name: "Šempeter pri Gorici", post_num: 5290},
  {name: "Šempeter v Savinjski dolini", post_num: 3311},
  {name: "Šenčur", post_num: 4208},
  {name: "Šentilj v Slovenskih goricah", post_num: 2212},
  {name: "Šentjanž", post_num: 8297},
  {name: "Šentjanž pri Dravogradu", post_num: 2373},
  {name: "Šentjernej", post_num: 8310},
  {name: "Šentjur", post_num: 3230},
  {name: "Šentrupert", post_num: 3271},
  {name: "Šentrupert", post_num: 8232},
  {name: "Šentvid pri Stični", post_num: 1296},
  {name: "Škocjan", post_num: 8275},
  {name: "Škofije", post_num: 6281},
  {name: "Škofja Loka", post_num: 4220},
  {name: "Škofja vas", post_num: 3211},
  {name: "Škofljica", post_num: 1291},
  {name: "Šmarje", post_num: 6274},
  {name: "Šmarje - Sap", post_num: 1293},
  {name: "Šmarje pri Jelšah", post_num: 3240},
  {name: "Šmarješke Toplice", post_num: 8220},
  {name: "Šmartno na Pohorju", post_num: 2315},
  {name: "Šmartno ob Dreti", post_num: 3341},
  {name: "Šmartno ob Paki", post_num: 3327},
  {name: "Šmartno pri Litiji", post_num: 1275},
  {name: "Šmartno pri Slovenj Gradcu", post_num: 2383},
  {name: "Šmartno v Rožni dolini", post_num: 3201},
  {name: "Šoštanj", post_num: 3325},
  {name: "Štanjel", post_num: 6222},
  {name: "Štore", post_num: 3220},
  {name: "Tabor", post_num: 3304},
  {name: "Teharje", post_num: 3221},
  {name: "Tišina", post_num: 9251},
  {name: "Tolmin", post_num: 5220},
  {name: "Topolšica", post_num: 3326},
  {name: "Trbonje", post_num: 2371},
  {name: "Trbovlje", post_num: 1420},
  {name: "Trebelno ", post_num: 8231},
  {name: "Trebnje", post_num: 8210},
  {name: "Trnovo pri Gorici", post_num: 5252},
  {name: "Trnovska vas", post_num: 2254},
  {name: "Trojane", post_num: 1222},
  {name: "Trzin", post_num: 1236},
  {name: "Tržič", post_num: 4290},
  {name: "Tržišče", post_num: 8295},
  {name: "Turjak", post_num: 1311},
  {name: "Turnišče", post_num: 9224},
  {name: "Uršna sela", post_num: 8323},
  {name: "Vače", post_num: 1252},
  {name: "Velenje ", post_num: 3320},
  {name: "Velenje2", post_num: 3322},
  {name: "Velika Loka", post_num: 8212},
  {name: "Velika Nedelja", post_num: 2274},
  {name: "Velika Polana", post_num: 9225},
  {name: "Velike Lašče", post_num: 1315},
  {name: "Veliki Gaber", post_num: 8213},
  {name: "Veržej", post_num: 9241},
  {name: "Videm - Dobrepolje", post_num: 1312},
  {name: "Videm pri Ptuju", post_num: 2284},
  {name: "Vinica", post_num: 8344},
  {name: "Vipava", post_num: 5271},
  {name: "Visoko", post_num: 4212},
  {name: "Višnja Gora", post_num: 1294},
  {name: "Vitanje", post_num: 3205},
  {name: "Vitomarci", post_num: 2255},
  {name: "Vodice", post_num: 1217},
  {name: "Vojnik", post_num: 3212},
  {name: "Volčja Draga", post_num: 5293},
  {name: "Voličina", post_num: 2232},
  {name: "Vransko", post_num: 3305},
  {name: "Vremski Britof", post_num: 6217},
  {name: "Vrhnika", post_num: 1360},
  {name: "Vuhred", post_num: 2365},
  {name: "Vuzenica", post_num: 2367},
  {name: "Zabukovje ", post_num: 8292},
  {name: "Zagorje ob Savi", post_num: 1410},
  {name: "Zagradec", post_num: 1303},
  {name: "Zavrč", post_num: 2283},
  {name: "Zdole ", post_num: 8272},
  {name: "Zgornja Besnica", post_num: 4201},
  {name: "Zgornja Korena", post_num: 2242},
  {name: "Zgornja Kungota", post_num: 2201},
  {name: "Zgornja Ložnica", post_num: 2316},
  {name: "Zgornja Polskava", post_num: 2314},
  {name: "Zgornja Velka", post_num: 2213},
  {name: "Zgornje Gorje", post_num: 4247},
  {name: "Zgornje Jezersko", post_num: 4206},
  {name: "Zgornji Leskovec", post_num: 2285},
  {name: "Zidani Most", post_num: 1432},
  {name: "Zreče", post_num: 3214},
  {name: "Žabnica", post_num: 4209},
  {name: "Žalec", post_num: 3310},
  {name: "Železniki", post_num: 4228},
  {name: "Žetale", post_num: 2287},
  {name: "Žiri", post_num: 4226},
  {name: "Žirovnica", post_num: 4274},
  {name: "Žužemberk", post_num: 8360}
])
User.create!([
  {first_name: nil, last_name: nil, phone: nil, username: nil, password_digest: "$2a$10$qE25RTdgM53.zTUesHIBI.84aKYNpdK1lH5ekHSgZue81SODpQota", email: "matanusig@uemail99.com"}
])
Ride.create!([
  {max_people: 4, desc_car: "", price: "6", insurance: 0, user_id: 5, start_id: 321, end_id: 222, desc: "", phone_num: nil, rdate: "2018-04-02", time: "7:25"},
  {max_people: 3, desc_car: "Tesla Model X - Črn", price: "4", insurance: 1, user_id: 5, start_id: 123, end_id: 213, desc: "asdaifhjashasj", phone_num: nil, rdate: "2018-04-03", time: "7:20"}
])
